### ISSUE TITLE
I can't install kinefx_tools

### ISSUE THREAD

**Issue by cgdept** [kamilhepner/kinefx_tools#4]
Hello! When I try make last step (create shelf and button) I got error, like : Traceback (most recent call last):
  File "kinefx_tools", line 3, in <module>
ImportError: No module named kinefx_tools

I cheked all paths and re read your manual (but nothing happened)

please help!) 
Thank you!

**Comment by kamilhepner** [comment]
Happy to see that got sorted! :)
