### ISSUE TITLE
hda's released under limited commercial license

### ISSUE THREAD

**Issue by danmacnish** [kamilhepner/kinefx_tools#5]
Hey Kamil, your kinefx tools are super useful, amazing work! Is there any chance you'd consider releasing the HDA's under the full houdini license (i.e. with a .hda extension instead of .hdalc)?

I'd be happy to pay if you released them on gumroad or similar.

**Comment by netlander** [comment]
Haven't installed these tools yet..

Do you mean that they come in as .hdalc which makes them useless on a fully licensed Houdini?

If that's the case I don't see any point in installing them.

**Comment by kamilhepner** [comment]
Yes, they're free tools saved as .hdalc. In the future, I'm planning to release them under a full commercial license.
