### ISSUE TITLE
Attach Control Geometry 1.2 issue with Houdini 19.0.455

### ISSUE THREAD

**Issue by akiraendo1** [kamilhepner/kinefx_tools#6]
Attach Control Geometry 1.2 does not work with Houdini 19 anymore.
I think SideFX changed some library names in Houdini 19.
So Python code needs update to import to "utils" instead of "kinefx_utils".
-> "from kinefx import utils"

**Comment by kamilhepner** [comment]
Thanks for flagging in it. I've been working on a new update to accommodate changes in H19.

**Comment by akiraendo1** [comment]
Hi Kamil,

i really like your tutorial on cgcircuit.
When i came across the usage of your great HDAs and scripts, it was not so easy for me to find out how to get it to work.
I’m on a mac with houdini 19 py3. I thought that might be the problem.
Finally i got them somewhat working.

Anyway, i appreciate your great work.
I would love to see how you would use mixamo-anims and a proper motion-retargeting workflow and adjusting motionclips in houdini with kinefx.

Thanks!

Best,
Akira


Akira Endo • creative director • digital artist
-
phone +49 89 89058025
mobile +49 172 5633738
***@***.***
www.akira-endo.com
-
Türkenstraße 61
80799 München
-
USt-Id Nr. DE235061532

**Comment by kamilhepner** [comment]
Hi Akira,

Happy to hear that you've enjoyed the tutorial and tools. I'm currently
working on updating everything to* H19*, sidefx did quite a few changes and
I need to fix some of HDA's. For now, if you are keen to use tools you can
try switching back to *H18.5  *I know it isn't ideal but soon I should
release an update and extra tutorial videos.

Cheers,
Kamil

**Comment by kamilhepner** [comment]
Attach control geometry node has been replaced with new Attach obj control

**Comment by kamilhepner** [comment]
Fixed in latest release

**Comment by wilcoxlor** [comment]
hi Kamil, same problem here on houdini 19.5 Iàm getting this error :

Error 
Invalid source /obj/subnet1/rig/attachcontrolgeo_custom1/python1
Error: Python error: Traceback (most recent call last):
File "<stdin>", line 3, in <module>
ImportError: cannot import name 'kinefx_utils' from 'kinefx' (C:\PROGRA~1/SIDEEF~1/Houdini 19.5.303/packages/kinefx/python3.9libs\kinefx\__init__.py)
. 
thanks so mutch
wil.
